### PR TITLE
Add setuptools build structure

### LINKED ISSUE #35: Add setuptools/poetry build script
It would be great to have a `setup.py` (setuptools) or `pyproject.toml` (for poetry) to make building/installing this 'package' on different platforms much easier (I'm thinking about Windows in particular here), rather than manually copying files to the target directories.

If @DrDaveD is open to that I can write up a prototype and propose a pull request.

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR fixes #35 by adding setuptools build metadata for this project.

I have **no idea** how this will interfere with the RPM build, I do not understand that spec file at all.

### CODE REVIEW

**Comment by DrDaveD** [comment]
I'm sorry about the delay, I was away.

Since this only adds files, it should have no effect on the rpmbuild.

However, it's not clear to me what the added value is.  What do you plan to do with the setuptools build structure?  I would be concerned about accidentally breaking it, since I never use it.   Perhaps it is time to add some github actions at least to make sure that things build on every PR.

**Comment by DrDaveD** [comment]
Oh, from #35 you talked about making it easier to build on Windows. 

It won't be very easy for me to test it on Windows, but maybe you could at least add to the RELEASE_PROCEDURE file the steps I should do to update it when there's a new version including a way to test it.

**Comment by DrDaveD** [comment]
@duncanmmacleod This is still pending because you didn't answer my questions.

**Comment by duncanmmacleod** [comment]
@DrDaveD, sorry for the extended delay.

My plan with this is to eventually have `htgettoken` provide a pure-Python API as well as a command-line interface, vaguely something like

```python
from htgettoken import get_token

get_token(scopes=["read:/frames"], audience="ANY", vault="vault.ligo.org")
```

However I am aware that this would be a significant departure from the current model. If you would prefer I am happy to start with a separate project that provides this, and possibly merge things further down the road; or I'm happy to start down this path with small steps, the first of which would be exactly what you suggested, add some github actions.

**Comment by duncanmmacleod** [comment]
Actually, I would be very hesitant working in a separate project, I have no real idea how htgettoken works, and keeping up with any changes you would make would be hard.

**Comment by DrDaveD** [comment]
Let's work together on this project.  That way whatever improvements you make will benefit all the users.

**Comment by duncanmmacleod** [comment]
This has been rebased against #56, so now includes modifications to the RPM spec file.

I also added basic tests on Windows and Python 3.11.

**Comment by duncanmmacleod** [comment]
@DrDaveD, this has been rebased now that #56 has been merged. Currently it doesn't really _do_ anything, so if you want to release without it that's fine.

The next step would be to translate `htgettoken` the script into `htgettoken.py` (a module), but I am hesitant to try and do too many things all at once. If you would rather 'get it done' I am happy to add that to this PR.

**Review by DrDaveD — APPROVED** [review]

**Pull request merged**
